version: '3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customerdb
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: springboot-packers-movers
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net:
